### ISSUE TITLE
Sunton 8048s070C: Antiburn working only partially

### ISSUE THREAD

**Issue by The-May** [HASwitchPlate/openHASP#764]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://www.openhasp.com/)
- [x] Update openHASP to the latest version
- [x] Reproduce the issue and describe all steps

### Describe the bug

Whenever I start anti burn it only works for almost half of the screen.

### To Reproduce

Flashed with the nightly web installer:
openHASP
Version	0.7.0-rc12 cd34d89
Build DateTime	May 23 2024 22:27:05 UTC
Environment	sunton-8048s070c_16MB
Uptime	7m 2s
Idle	off
Active Page	1
Device Memory
Free Heap	76.65 KiB
Free Block	67.98 KiB
Fragmentation	11%
PSRam Free	7.23 MiB
PSRam Size	7.99 MiB
LVGL Memory
Total	64.00 KiB
Free	52.25 KiB
Fragmentation	1%
MQTT
[...]
Wifi
[...]
Module
Model	ESP32-S3 rev0
Frequency	240MHz
Core Version	4.4.6
Reset Reason	CPU0: SW_CPU_RESET / CPU1: SW_CPU_RESET
Flash Size	16.00 MiB
Program Size Used	1.55 MiB
Program Size Free	1.93 MiB
Filesystem Size	11.93 MiB
Filesystem Used	20.00 KiB
Filesystem Free	11.91 MiB

after that I configured MQTT, setup screen rotation to 270° and changed hostname of the esp.
Then I integrated everything and went to homeassistant -> toggle switch
![image](https://github.com/user-attachments/assets/e85905d8-1e9c-4730-93fe-c0d82075884f)

no json issue, general issue

### Expected behavior

Burn In should be on whole screen and not partially

### Screenshots or video

![image](https://github.com/user-attachments/assets/e9d9e47c-80a9-41e0-acb1-d346b2611c34)

**Comment by The-May** [comment]
For some Reason, my whole issue was omitted not saved:
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://www.openhasp.com/)
- [x] Update openHASP to the latest version
- [x] Reproduce the issue and describe all steps

### Describe the bug


### To Reproduce
<!--

Flashed with the nightly web installer:
openHASP
Version	0.7.0-rc12 cd34d89
Build DateTime	May 23 2024 22:27:05 UTC
Environment	sunton-8048s070c_16MB
Uptime	7m 2s
Idle	off
Active Page	1
Device Memory
Free Heap	76.65 KiB
Free Block	67.98 KiB
Fragmentation	11%
PSRam Free	7.23 MiB
PSRam Size	7.99 MiB
LVGL Memory
Total	64.00 KiB
Free	52.25 KiB
Fragmentation	1%
MQTT
[...]
Wifi
[...]
Module
Model	ESP32-S3 rev0
Frequency	240MHz
Core Version	4.4.6
Reset Reason	CPU0: SW_CPU_RESET / CPU1: SW_CPU_RESET
Flash Size	16.00 MiB
Program Size Used	1.55 MiB
Program Size Free	1.93 MiB
Filesystem Size	11.93 MiB
Filesystem Used	20.00 KiB
Filesystem Free	11.91 MiB

after that I configured MQTT, setup screen rotation to 270° and changed hostname of the esp.
Then I go To homeassistant -> toggle switch
![image](https://github.com/user-attachments/assets/e85905d8-1e9c-4730-93fe-c0d82075884f)

```json
-> no json issue, general issue
-->

### Expected behavior
<!--
Burn In should be on whole screen and not partially
-->

### Screenshots or video
<!--
![image](https://github.com/user-attachments/assets/e9d9e47c-80a9-41e0-acb1-d346b2611c34)
-->

**Comment by fvanroie** [comment]
This should now be fixed in the latest master: https://github.com/HASwitchPlate/openHASP/actions/runs/10540465094

**Comment by The-May** [comment]
@fvanroie 

Cant confirm it. Issue seems to still persist. (Dont get irritiated by it - rotation is 90° here and was 270 before)

![image](https://github.com/user-attachments/assets/dc902a46-6dc5-4096-b1d1-4a154bba9be6)


It looks like the nightly build for Sunton 8048S070C seems to not use the fix yet.

![image](https://github.com/user-attachments/assets/e1dfc9ce-c49f-43d1-9ecb-1b85565a4956)

**Comment by fvanroie** [comment]
That's an old nightly build date. You need to download the latest sunton.zip from the [GitHub Actions](https://github.com/HASwitchPlate/openHASP/actions/runs/10654822394).

**Comment by The-May** [comment]
I downloaded the latest build from the Github Actions and it seems to work now.
![image](https://github.com/user-attachments/assets/768f6433-f548-43f3-baed-c0cb14b366c8)

![image](https://github.com/user-attachments/assets/e3acd123-de49-4132-9c15-e0e26e9bdb69)

**Comment by The-May** [comment]
Works now, thanks.

**Comment by fvanroie** [comment]
Great! Thanks for testing and confirming
